This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./ebt.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file ebt.acn....done (72 entries accepted, 0 rejected).
Sorting entries....done (453 comparisons).
Generating output file ebt.acr....done (98 lines written, 0 warnings).
Output written in ebt.acr.
Transcript written in ebt.alg.
